const KEY="diddyPartyDemoV1";
const defaults={session:{date:"",venue:"Your usual pitch"},result:{home:6,away:4,note:"A tactical masterclass. Allegedly."},players:[{id:1,name:"Geraldo",nickname:"The Finisher-ish",position:"ST",rating:87,emoji:"⚡",goals:12,assists:5,pace:89,shooting:86,passing:72,defending:31},{id:2,name:"Luca",nickname:"The Silk Merchant",position:"LW",rating:82,emoji:"🪄",goals:9,assists:7,pace:91,shooting:78,passing:83,defending:40},{id:3,name:"Mpho",nickname:"The Sprinter",position:"RW",rating:80,emoji:"🚀",goals:7,assists:3,pace:94,shooting:76,passing:69,defending:38},{id:4,name:"Tariq",nickname:"The Playmaker",position:"CM",rating:78,emoji:"🧠",goals:5,assists:6,pace:73,shooting:67,passing:88,defending:65},{id:5,name:"Dan",nickname:"The Wall (sometimes)",position:"CB",rating:76,emoji:"🧱",goals:2,assists:2,pace:61,shooting:54,passing:69,defending:84},{id:6,name:"Stefan",nickname:"Defensive Liability",position:"GK",rating:74,emoji:"🧤",goals:1,assists:0,pace:49,shooting:30,passing:55,defending:87},{id:7,name:"Kyle",nickname:"Shot Stopper-ish",position:"GK",rating:72,emoji:"🦖",goals:1,assists:1,pace:55,shooting:35,passing:51,defending:82}],votes:{},ownGoals:2,cleanSheets:4};
const clone=x=>JSON.parse(JSON.stringify(x));let data=load();let toastTimer;
function load(){try{const s=localStorage.getItem(KEY);if(!s)return clone(defaults);const p=JSON.parse(s);return {...clone(defaults),...p,players:Array.isArray(p.players)?p.players:clone(defaults.players)}}catch{return clone(defaults)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{toast("Browser storage unavailable; changes may not persist.")}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(msg){const el=document.querySelector("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2800)}
function num(id,min,max){const el=document.getElementById(id),n=Number(el.value);if(el.value===""||!Number.isInteger(n)||n<min||n>max)throw Error(`${el.labels?.[0]?.textContent||id}: enter a whole number from ${min} to ${max}.`);return n}
function render(){document.querySelector("#summaryPlayers").textContent=data.players.length;document.querySelector("#summaryGoals").textContent=data.players.reduce((s,p)=>s+(+p.goals||0),0);document.querySelector("#summaryAssists").textContent=data.players.reduce((s,p)=>s+(+p.assists||0),0);document.querySelector("#adminPlayerList").innerHTML=data.players.length?data.players.map(p=>`<article class="admin-player-row"><span class="admin-player-emoji">${esc(p.emoji||"⚽")}</span><div class="admin-player-info"><strong>${esc(p.name)}</strong><small>${esc(p.nickname||"No nickname")} · ${esc(p.position)} · OVR ${p.rating} · ⚽ ${p.goals} · 🪄 ${p.assists}</small></div><div class="admin-player-actions"><button type="button" data-edit="${p.id}">Edit</button><button type="button" class="delete-player" data-delete="${p.id}">×</button></div></article>`).join(""):'<div class="empty-state">No players yet. Add the first menace above.</div>';document.querySelector("#matchStatsFields").innerHTML=data.players.map(p=>`<div class="match-stat-row"><span class="match-stat-name">${esc(p.emoji||"⚽")} ${esc(p.name)}</span><div><label for="g${p.id}">Goals</label><input id="g${p.id}" type="number" min="0" max="99" value="0" data-g="${p.id}"></div><div><label for="a${p.id}">Assists</label><input id="a${p.id}" type="number" min="0" max="99" value="0" data-a="${p.id}"></div></div>`).join("")}
function resetForm(){document.querySelector("#playerForm").reset();document.querySelector("#playerId").value="";document.querySelector("#playerEmoji").value="⚽";["playerRating"].forEach(id=>document.getElementById(id).value=75);["playerPace","playerShooting","playerPassing","playerDefending"].forEach(id=>document.getElementById(id).value=70);document.querySelector("#playerGoals").value=0;document.querySelector("#playerAssists").value=0;document.querySelector("#savePlayerBtn").textContent="＋ Add player";document.querySelector("#cancelEditBtn").hidden=true}
function edit(id){const p=data.players.find(x=>x.id===+id);if(!p)return;const map={playerId:"id",playerName:"name",playerNickname:"nickname",playerPosition:"position",playerEmoji:"emoji",playerRating:"rating",playerGoals:"goals",playerAssists:"assists",playerPace:"pace",playerShooting:"shooting",playerPassing:"passing",playerDefending:"defending"};Object.entries(map).forEach(([field,key])=>document.getElementById(field).value=p[key]??"");document.querySelector("#savePlayerBtn").textContent="Save player changes";document.querySelector("#cancelEditBtn").hidden=false;document.querySelector("#playerManagement").scrollIntoView({behavior:"smooth"})}
document.querySelector("#playerForm").addEventListener("submit",e=>{e.preventDefault();try{const name=document.querySelector("#playerName").value.trim();if(!name)throw Error("Player name is required.");const oldId=document.querySelector("#playerId").value;const p={id:oldId?+oldId:Math.max(0,...data.players.map(x=>+x.id||0))+1,name,nickname:document.querySelector("#playerNickname").value.trim(),position:document.querySelector("#playerPosition").value,emoji:document.querySelector("#playerEmoji").value.trim()||"⚽",rating:num("playerRating",1,99),goals:num("playerGoals",0,9999),assists:num("playerAssists",0,9999),pace:num("playerPace",1,99),shooting:num("playerShooting",1,99),passing:num("playerPassing",1,99),defending:num("playerDefending",1,99)};const i=data.players.findIndex(x=>x.id===p.id);if(i<0)data.players.push(p);else data.players[i]=p;save();render();resetForm();toast(i<0?"Player added to the circus. 🎪":"Player updated. Stats department online.")}catch(err){toast(err.message)}});
document.querySelector("#cancelEditBtn").addEventListener("click",resetForm);
document.querySelector("#adminPlayerList").addEventListener("click",e=>{const eb=e.target.closest("[data-edit]"),db=e.target.closest("[data-delete]");if(eb)return edit(eb.dataset.edit);if(db){const p=data.players.find(x=>x.id===+db.dataset.delete);if(!p||!confirm(`Remove ${p.name} from the squad?`))return;data.players=data.players.filter(x=>x.id!==p.id);delete data.votes[p.id];save();render();toast("Player removed from the squad.")}});
document.querySelector("#matchForm").addEventListener("submit",e=>{e.preventDefault();try{const home=num("matchHome",0,99),away=num("matchAway",0,99);const stats=data.players.map(p=>({id:p.id,g:num("g"+p.id,0,99),a:num("a"+p.id,0,99)}));const goals=stats.reduce((s,x)=>s+x.g,0);if(goals>home)throw Error(`Player goals (${goals}) exceed your team's score (${home}). Check entries.`);stats.forEach(x=>{const p=data.players.find(p=>p.id===x.id);p.goals+=x.g;p.assists+=x.a});data.result={home,away,note:document.querySelector("#matchNote").value.trim()||"Match logged. Details under investigation."};const venue=document.querySelector("#matchVenue").value.trim();if(venue)data.session.venue=venue;save();render();document.querySelector("#matchForm").reset();document.querySelector("#matchHome").value=0;document.querySelector("#matchAway").value=0;document.querySelectorAll("[data-g],[data-a]").forEach(x=>x.value=0);toast("Match logged! Check the homepage. ⚽")}catch(err){toast(err.message)}});
document.querySelector("#settingsForm").addEventListener("submit",e=>{e.preventDefault();try{data.cleanSheets=num("cleanSheetsInput",0,9999);data.ownGoals=num("ownGoalsInput",0,9999);save();toast("Season settings saved.")}catch(err){toast(err.message)}});
document.querySelector("#exportBtn").addEventListener("click",()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="the-diddy-party-backup.json";a.click();URL.revokeObjectURL(url);toast("Backup exported. Keep it safe.")});document.querySelector("#importBtn").addEventListener("click",()=>document.querySelector("#importFile").click());document.querySelector("#importFile").addEventListener("change",async e=>{const file=e.target.files?.[0];if(!file)return;try{const p=JSON.parse(await file.text());if(!p||!Array.isArray(p.players)||!p.result)throw Error("This doesn't look like a Diddy Party backup.");if(!confirm("Replace current browser data with this backup?"))return;data={...clone(defaults),...p};save();render();document.querySelector("#cleanSheetsInput").value=data.cleanSheets;document.querySelector("#ownGoalsInput").value=data.ownGoals;toast("Backup imported.")}catch(err){toast(err.message)}finally{e.target.value=""}});
document.querySelector("#resetAllBtn").addEventListener("click",()=>{if(!confirm("Reset all demo data in this browser? Export a backup first if needed."))return;data=clone(defaults);save();render();resetForm();document.querySelector("#cleanSheetsInput").value=data.cleanSheets;document.querySelector("#ownGoalsInput").value=data.ownGoals;toast("Demo data reset.")});document.querySelector("#menuToggle").addEventListener("click",()=>{const n=document.querySelector("#mainNav"),o=n.classList.toggle("open");document.querySelector("#menuToggle").setAttribute("aria-expanded",String(o))});document.querySelector("#cleanSheetsInput").value=data.cleanSheets;document.querySelector("#ownGoalsInput").value=data.ownGoals;render();
